'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:2.0.50727.8669
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System

Namespace My.Resources
    
    'This class was auto-generated by the StronglyTypedResourceBuilder
    'class via a tool like ResGen or Visual Studio.
    'To add or remove a member, edit your .ResX file then rerun ResGen
    'with the /str option, or rebuild your VS project.
    '''<summary>
    '''  A strongly-typed resource class, for looking up localized strings, etc.
    '''</summary>
    <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "2.0.0.0"),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute(),  _
     Global.Microsoft.VisualBasic.HideModuleNameAttribute()>  _
    Friend Module Resources
        
        Private resourceMan As Global.System.Resources.ResourceManager
        
        Private resourceCulture As Global.System.Globalization.CultureInfo
        
        '''<summary>
        '''  Returns the cached ResourceManager instance used by this class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend ReadOnly Property ResourceManager() As Global.System.Resources.ResourceManager
            Get
                If Object.ReferenceEquals(resourceMan, Nothing) Then
                    Dim temp As Global.System.Resources.ResourceManager = New Global.System.Resources.ResourceManager("Gemstone_Management.Resources", GetType(Resources).Assembly)
                    resourceMan = temp
                End If
                Return resourceMan
            End Get
        End Property
        
        '''<summary>
        '''  Overrides the current thread's CurrentUICulture property for all
        '''  resource lookups using this strongly typed resource class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend Property Culture() As Global.System.Globalization.CultureInfo
            Get
                Return resourceCulture
            End Get
            Set
                resourceCulture = value
            End Set
        End Property
        
        Friend ReadOnly Property _1459086936_diamond() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("1459086936_diamond", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property _1459087017_application_view_detail() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("1459087017_application_view_detail", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property _1459087233_client_account_template() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("1459087233_client_account_template", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property _1459087318_group() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("1459087318_group", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property _1459087451_json() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("1459087451_json", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property _1459087549_user_group() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("1459087549_user-group", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property _1459087690_Add_Male_User() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("1459087690_Add-Male-User", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property _1459087737_block_user() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("1459087737_block_user", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property _1459087865_application_pgp_signature() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("1459087865_application-pgp-signature", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property _1459088001_on_off() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("1459088001_on-off", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property _1459088001_on_off1() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("1459088001_on-off1", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property _1459088068_Delete() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("1459088068_Delete", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property _1459088068_Delete1() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("1459088068_Delete1", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property _1459088370_diamond_gem_ruby() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("1459088370_diamond_gem_ruby", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property _1459088436_stocks_ios7_ios_7() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("1459088436_stocks_ios7_ios_7", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property _1459088971_add_buy_plus_shopping_cart() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("1459088971_add-buy-plus-shopping-cart", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property _1459089293_Delete() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("1459089293_Delete", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property _1459089467_magnifier() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("1459089467_magnifier", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property _1459089467_magnifier1() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("1459089467_magnifier1", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property _1459089683_tick_red() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("1459089683_tick_red", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property _1459089777_arrow_right() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("1459089777_arrow-right", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property _1459089777_arrow_right1() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("1459089777_arrow-right1", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property _1459090208_drawing_23() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("1459090208_drawing-23", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property _1459090330_Update() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("1459090330_Update", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property _1459091596_Error() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("1459091596_Error", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property _1459192080_other_arrow_left_other_glyph() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("1459192080_other-arrow-left-other-glyph", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property _1459192535_vector_65_03() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("1459192535_vector_65_03", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property _1459192746_checked_2() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("1459192746_checked-2", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property _1459193563_ic_sort_48px() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("1459193563_ic_sort_48px", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property _1459193563_ic_sort_48px1() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("1459193563_ic_sort_48px1", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property _1459636952_vector_65_01() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("1459636952_vector_65_01", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property _1459637439_Diagram() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("1459637439_Diagram", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property _1459637597_Credit_report() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("1459637597_Credit_report", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property _1459637787_clipboard() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("1459637787_clipboard", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property _1459637960_document() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("1459637960_document", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property _1459640475_Bar_Chart() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("1459640475_Bar Chart", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property _1459797628_chart() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("1459797628_chart", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property _1459797713_device_board_presentation_content_chart_glyph() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("1459797713_device-board-presentation-content-chart-glyph", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property _1459804286_reload_512x512px() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("1459804286_reload-512x512px", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property _1459804473_update() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("1459804473_update", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property _1459804473_update1() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("1459804473_update1", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property administrator() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("administrator", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property chart_4_512() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("chart_4-512", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property contact_details__ios_7_interface_symbol_318_33582() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("contact-details--ios-7-interface-symbol_318-33582", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property Delete_5() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Delete 5", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property Delete_51() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Delete 51", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property delete_user() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("delete user", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property fdff() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("fdff", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property Gemsnm() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Gemsnm", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property home() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("home", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property images__2_() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("images (2)", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property logout__ios_7_interface_symbol_318_33643() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("logout--ios-7-interface-symbol_318-33643", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property logout__ios_7_interface_symbol_318_336431() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("logout--ios-7-interface-symbol_318-336431", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property m___() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("m,,,", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property new_user() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("new user", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property new_user1() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("new user1", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property oAccess() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("oAccess", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property output_RO3ecU() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("output_RO3ecU", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property output_z1Owd8() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("output_z1Owd8", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property payroll_01() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("payroll_01", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property printer__1_() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("printer (1)", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property Register() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Register", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property Remove() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Remove", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property Remove1() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Remove1", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property tarjeta_de_identificacion_profesional_318_38534() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("tarjeta-de-identificacion-profesional_318-38534", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property User_Clients_icon() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("User-Clients-icon", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property warning_icon_hi() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("warning-icon-hi", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
    End Module
End Namespace
